version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/rag-system/requirements.txt" # Location of your `requirements.txt` or `setup.py`
    schedule:
      interval: "daily" # Options: "daily", "weekly", "monthly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "some-dependency-to-ignore"
        versions: ["< 1.0.0"] # Optional: ignore specific versions

  - package-ecosystem: "pip"
    directory: "/rag-system/requirements.txt" # Location of your `requirements-dev.txt` or other dependency files
    schedule:
      interval: "daily" # Options: "daily", "weekly", "monthly"
    allow:
      - dependency-type: "dev"
    ignore:
      - dependency-name: "another-dependency-to-ignore"
        versions: ["< 2.0.0"] # Optional: ignore specific versions
